- include_role:
    name: korbad.facts.active_user_environment_dict

- name: Get xrandr info
  command: xrandr
  register: xrandr_output
  environment:
    DISPLAY: "{{ active_user_environ_dict.DISPLAY }}"

- set_fact:
    unstructured_xrandr: "{{ xrandr_output.stdout }}"
    cacheable: true
